name: cooking
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/wood.jpg
   - assets/huevos.jpg
   - assets/chiles.jpg
   - assets/pozole.jpg
   - assets/fondo.jpg
   - assets/grunge.jpg
   
  fonts:
     - family: mermaid
       fonts:
         - asset: assets/Mermaid1001.ttf
     - family: bebas-neue
       fonts:
         - asset: assets/BebasNeue-Regular.ttf
